apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: reliability-lab

spec:
  # replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "fastapi-role"
        vault.hashicorp.com/agent-inject-secret-db-config: "secret/data/db-pass"
        # This template formats the secret into a file the app can read
        vault.hashicorp.com/agent-inject-template-db-config: |
          {{- with secret "secret/data/db-pass" -}}
          export POSTGRES_USER="{{ .Data.data.user }}"
          export POSTGRES_PASSWORD="{{ .Data.data.password }}"
          export POSTGRES_DB="testdb"
          {{- end -}}
    spec:
      serviceAccountName: fastapi-sa
      containers:
      - name: fastapi
        image: abbasaziz/fastapi-slo:trace-test
        command: ["/bin/sh", "-c"]
        args:
          - |
            sleep 2;
            if [ -f /vault/secrets/db-config ]; then
              . /vault/secrets/db-config;
              # 'exec' makes Python the main process
              exec python main.py; 
            else
              echo "Vault file missing";
              exit 1;
            fi
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: OTEL_PYTHON_LOG_LEVEL
          value: "debug"
        livenessProbe:
          httpGet:
            path: /live
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"     # 100 milli-cores (0.1 CPU)
            memory: "128Mi"
          limits:
            cpu: "500m"     # Allow bursting
            memory: "256Mi"
